dist: trusty
sudo: false

branches:
  only:
  - master

language: go

go:
  - "1.14.x"

before_install:
  - go get github.com/mattn/goveralls

install:
  - make deps

script:
  - hack/verify-codegen.sh
  - travis_wait 20 goveralls -service=travis-ci -package ./pkg/... -v
  - make e2e
