dist: trusty
sudo: false

branches:
  only:
  - master

language: go

go:
  - "1.10.x"

before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls

install:
  - make deps

script:
  - travis_wait 20 goveralls -service=travis-ci -package ./pkg/... -v
