image:
  registry: registry.opensource.zalan.do
  repository: acid/postgres-operator
  tag: v1.1.0
  pullPolicy: "IfNotPresent"

# Optionally specify an array of imagePullSecrets.
# Secrets must be manually created in the namespace.
# ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
# imagePullSecrets:
  # - name: myRegistryKeySecretName

podAnnotations: {}
podLabels: {}

config:
  watched_namespace: "*" # listen to all namespaces
  cluster_labels: application:spilo
  cluster_name_label: version
  pod_role_label: spilo-role

  debug_logging: "true"
  workers: "4"
  docker_image: registry.opensource.zalan.do/acid/spilo-cdp-11:1.5-p70
  secret_name_template: '{username}.{cluster}.credentials'
  super_username: postgres
  enable_teams_api: "false"
  spilo_privileged: "false"
  # set_memory_request_to_limit: "true"
  # postgres_superuser_teams: "postgres_superusers"
  # enable_team_superuser: "false"
  # team_admin_role: "admin"
  # teams_api_url: http://fake-teams-api.default.svc.cluster.local
  # team_api_role_configuration: "log_statement:all"
  # infrastructure_roles_secret_name: postgresql-infrastructure-roles
  # oauth_token_secret_name: postgresql-operator
  # pam_role_name: zalandos
  # pam_configuration: |
  #  https://info.example.com/oauth2/tokeninfo?access_token= uid realm=/employees
  # inherited_labels: ""
  aws_region: eu-central-1
  db_hosted_zone: db.example.com
  master_dns_name_format: '{cluster}.{team}.staging.{hostedzone}'
  replica_dns_name_format: '{cluster}-repl.{team}.staging.{hostedzone}'
  enable_master_load_balancer: "true"
  enable_replica_load_balancer: "false"

  pdb_name_format: "postgres-{cluster}-pdb"

  api_port: "8080"
  ring_log_lines: "100"
  cluster_history_entries: "1000"
  pod_terminate_grace_period: 5m
  pod_deletion_wait_timeout: 10m
  pod_label_wait_timeout: 10m
  ready_wait_interval: 3s
  ready_wait_timeout: 30s
  replication_username: standby
  resource_check_interval: 3s
  resource_check_timeout: 10m
  resync_period: 5m
  pod_management_policy: "ordered_ready"
  enable_pod_antiaffinity: "false"
  pod_antiaffinity_topology_key: "kubernetes.io/hostname"
rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

priorityClassName: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 300Mi
  # requests:
  #   cpu: 100m
  #   memory: 300Mi

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}
