apiVersion: v1
data:
  # required format (w/o quotes): 'propertyNumber: value'
  # allowed properties: 'user', 'password', 'inrole'
  # numbers >= 1 are mandatory
  
  # robot_zmon_acid_monitoring
  user1: cm9ib3Rfem1vbl9hY2lkX21vbml0b3Jpbmc=
  # robot_zmon
  inrole1: cm9ib3Rfem1vbg==
  # testuser
  user2: dGVzdHVzZXI=
  # foobar
  password2: c2VjcmV0
  # user batman with the password justice
  # looks for defails in the infrastructure roles configmap
  batman: anVzdGljZQ==
kind: Secret
metadata:
  name: postgresql-infrastructure-roles
  namespace: default
type: Opaque
