apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: default
spec:
  teamId: "ACID"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  postgresql:
    version: "11"
    parameters:
      shared_buffers: "32MB"
      max_connections: "10"
      log_checkpoints: "off"
      log_connections: "off"
      log_disconnections: "off"
      log_statement: "off"
