apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres-operator
    spec:
      serviceAccountName: operator
      containers:
      - name: postgres-operator
        image: pierone.example.com/acid/postgres-operator:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_MAP_NAME
          value: "postgres-operator"
