apiVersion: "acid.zalan.do/v1"
kind: "Postgresql"

metadata:
  name: acid-testcluster
spec:
  teamId: "ACID"
  volume:
    size: 5Gi
  numberOfInstances: 2
  users: #Application/Robot users
    zalando:
    - superuser
    - createdb
  allowedSourceRanges: #Load balancer source ranges
  - 127.0.0.1/32

#Expert section
  postgresql:
    version: "9.6"
    parameters:
      shared_buffers: "32MB"
      max_connections: "10"
      log_statement: "all"
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 300m
      memory: 3000Mi
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
    - hostssl all all 0.0.0.0/0 md5
    - host    all all 0.0.0.0/0 md5
    ttl: 30
    loop_wait: &loop_wait 10
    retry_timeout: 10
    maximum_lag_on_failover: 33554432
    useLoadBalancer: true
  maintenanceWindows:
  - 01:00-06:00 #UTC
  - Sat:00:00-04:00
