apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresqls.acid.zalan.do
  labels:
    app.kubernetes.io/name: postgres-operator
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: acid.zalan.do
  names:
    kind: postgresql
    listKind: postgresqlList
    plural: postgresqls
    singular: postgresql
    shortNames:
    - pg
  additionalPrinterColumns:
  - name: Team
    type: string
    description: Team responsible for Postgres CLuster
    JSONPath: .spec.teamId
  - name: Version
    type: string
    description: PostgreSQL version
    JSONPath: .spec.postgresql.version
  - name: Pods
    type: integer
    description: Number of Pods per Postgres cluster
    JSONPath: .spec.numberOfInstances
  - name: Volume
    type: string
    description: Size of the bound volume
    JSONPath: .spec.volume.size
  - name: CPU-Request
    type: string
    description: Requested CPU for Postgres containers
    JSONPath: .spec.resources.requests.cpu
  - name: Memory-Request
    type: string
    description: Requested memory for Postgres containers
    JSONPath: .spec.resources.requests.memory
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: Status
    type: string
    description: Current sync status of postgresql resource
    JSONPath: .status.PostgresClusterStatus
  scope: Namespaced
  subresources:
    status: {}
  version: v1
